//! Replay the retained-JavaScript refusal-wording oracle (slice 2). The three
//! expected strings come from `lib/engagement-store.js`'s own
//! `overCommitMessage`, pinned by sha256 in the fixture and regenerated by
//! `native/scripts/ceiling-vectors.mjs`.

use hagency_core::ceiling::{SpendContext, over_commit_message};

fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!(
        "../../hagency-store/tests/fixtures/ceiling-vectors.json"
    ))
    .unwrap()
}

fn message_vector(name: &str) -> serde_json::Value {
    fixture()["messages"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["name"] == name)
        .unwrap()
        .clone()
}

fn native(agent: &str, alloc: u64, remaining: u64, ctx: Option<&SpendContext>) -> String {
    over_commit_message(agent, alloc, remaining, ctx)
}

#[test]
fn native_ceiling_refusal_plain_form_without_context() {
    let vector = message_vector("plain-form");
    // A caller with no ledger still gets a usable error rather than a crash
    // or a fabricated breakdown: the context is optional by design.
    let produced = native(
        vector["agent"].as_str().unwrap(),
        vector["alloc"].as_u64().unwrap(),
        vector["remaining"].as_u64().unwrap(),
        None,
    );
    assert_eq!(produced, vector["expected"].as_str().unwrap());
    assert_eq!(produced, "allocating 500 would exceed the 100 left on a1");
}

#[test]
fn native_ceiling_refusal_names_binding_draw_preset_and_period() {
    let vector = message_vector("measured-binding");
    let context: SpendContext = serde_json::from_value(vector["context"].clone()).unwrap();
    let produced = native(
        vector["agent"].as_str().unwrap(),
        vector["alloc"].as_u64().unwrap(),
        vector["remaining"].as_u64().unwrap(),
        Some(&context),
    );
    assert_eq!(produced, vector["expected"].as_str().unwrap());
    // The operator-facing assertions the retained test pins, verbatim.
    assert!(produced.contains("10.0M"));
    assert!(produced.contains("250k is committed"));
    assert!(produced.contains("measured spend is what is binding"));
    assert!(produced.contains("2026-08"));
    assert!(produced.contains("codex-strong"));
    assert!(produced.contains("cache reads are measured and shown but do not draw"));
}

#[test]
fn native_ceiling_refusal_mirror_names_committed_without_cache_note() {
    let vector = message_vector("committed-binding-mirror");
    let context: SpendContext = serde_json::from_value(vector["context"].clone()).unwrap();
    let produced = native(
        vector["agent"].as_str().unwrap(),
        vector["alloc"].as_u64().unwrap(),
        vector["remaining"].as_u64().unwrap(),
        Some(&context),
    );
    assert_eq!(produced, vector["expected"].as_str().unwrap());
    // The mirror case: committed is the binding draw, and because consumed
    // equals spent there is no cache-read note to explain.
    assert!(produced.contains("committed allocations is what is binding"));
    assert!(!produced.contains("cache reads are measured"));
}
